CREATE DATABASE QL_DATVEXE
GO
USE QL_DATVEXE

-- Bảng nhân viên
GO
CREATE TABLE NHANVIEN (
    MANV INT IDENTITY(1,1)  PRIMARY KEY,
    TENNV NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
    GIOITINH NVARCHAR(5) NOT NULL,
    DIACHI NVARCHAR(50) NOT NULL,
    SDT NVARCHAR(11) NOT NULL UNIQUE,
    TrangThai NVARCHAR(50) DEFAULT N'Đang làm' -- TRẠNG THÁI ĐANG LÀM VÀ NGHỈ VIỆC
);

-- Bảng tài khoản nhân viên
GO
CREATE TABLE TAIKHOANNV (
    TAIKHOAN VARCHAR(50) PRIMARY KEY,
    MATKHAU VARCHAR(50) NOT NULL,
	MANV INT UNIQUE,
	QUYEN NVARCHAR(10) NOT NULL,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
);

-- Bảng khách hàng
GO
CREATE TABLE KHACHHANG (
    MAKH INT IDENTITY(1,1) PRIMARY KEY,
	TENKH  NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH NVARCHAR(5) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	SDT VARCHAR(11) NOT NULL,
	TAIKHOAN VARCHAR(50) NOT NULL UNIQUE,
	MATKHAU VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TRANGTHAI NVARCHAR DEFAULT N'Không khóa' -- TRẠNG THÁI KHÔNG KHÓA VÀ KHÓA
);

-- Bảng vé xe
GO
CREATE TABLE VEXE (
    MAVE INT IDENTITY(1,1) PRIMARY KEY,
	TENVE NVARCHAR(50) NOT NULL,
	GIAVE INT,
	DONVITINH NVARCHAR(50) NOT NULL,
	DIEMDON NVARCHAR(50) NOT NULL,
	DIEMDEN NVARCHAR(50) NOT NULL,
	THOIGIANDON NVARCHAR(50) NOT NULL,
    SOSAO INT,
	MOTA NVARCHAR(MAX) NOT NULL,
	HINHANH VARCHAR(50),
);

-- Bảng hoá đơn
GO
CREATE TABLE HOADON (
    MAHD INT IDENTITY(1,1)  PRIMARY KEY,
    MAKH INT NOT NULL,
    NGAYLAP DATETIME,
    THANHTIEN INT,
    TRANGTHAI bit DEFAULT 0, -- 0 Là hóa đơn chưa xác nhận, 1 là hóa được đã được xác nhận
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

-- Bảng chi tiết hoá đơn
GO
CREATE TABLE CHITIETHOADON (
    MAHD INT NOT NULL,
    MAVE INT NOT NULL,
    SOLUONG INT NOT NULL,
	PRIMARY KEY (MAHD, MAVE),
	FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	FOREIGN KEY (MAVE) REFERENCES VEXE(MAVE)
);

-- Bảng đánh giá
GO
CREATE TABLE DANHGIA (
    MAKH INT NOT NULL,
    MAVE INT NOT NULL,
    NOIDUNG NVARCHAR(MAX),
	SOSAO INT,
	NGAYDG DATETIME,
	PRIMARY KEY (MAKH, MAVE),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MAVE) REFERENCES VEXE(MAVE)
);

-- Bảng vé xe trong giỏ hàng
GO
CREATE TABLE VEXETRONGGIOHANG (
    MAVE INT NOT NULL,
    MAKH int NOT NULL,
	SOLUONG INT,
	PRIMARY KEY (MAVE, MAKH),
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	FOREIGN KEY (MAVE) REFERENCES VEXE(MAVE)
);

-- Bảng chi tiết xác nhận hoá đơn
GO
CREATE TABLE XACNHANHOADON (
    MAHD INT unique,
    MANV INT NOT NULL,
    NGAYXACNHAN DATETIME,
	PRIMARY KEY (MAHD, MANV),
	FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Bảng tin tức
GO
CREATE TABLE TINTUC (
    MATIN INT IDENTITY(1,1) PRIMARY KEY,
    TIEUDE NVARCHAR(50) NOT NULL,
    NOIDUNG NVARCHAR(MAX),
    NGAYDANG DATETIME,
    HINHANH VARCHAR(50)
);